<?php

function pum_expert_mycases_views_api() {
    return array('api' => 3.0);
}

function pum_expert_mycases_views_default_views() {
    $files = file_scan_directory(drupal_get_path('module', 'pum_expert_mycases'). '/views', '/.inc/');
    foreach ($files as $filepath => $file) {
        try {
            require $filepath;
            if (isset($view)) {
                $views[$view->name] = $view;
            }
        } catch (Exception $e) {
            //do nothing
        }
    }
    return $views;
}